---
name: Build

on:
  push:

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.14
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Build
        run: make build_all

      - name: Upload builds
        uses: actions/upload-artifact@v2.1.4
        with:
          name: builds
          path: bin/*
